lib/contacts_web/router.ex
defmodule ContactsWeb.Router do
  use ContactsWeb, :router

  import ContactsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ContactsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ContactsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/list", ContactController, :index


  end

  # Other scopes may use custom stacks.
  # scope "/api", ContactsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ContactsWeb.Telemetry

    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", ContactsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ContactsWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/contacts", ContactLive.Index, :index
    live "/contacts/new", ContactLive.Index, :new
    live "/contacts/:id/edit", ContactLive.Index, :edit

    live "/contacts/:id", ContactLive.Show, :show
    live "/contacts/:id/show/edit", ContactLive.Show, :edit

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ContactsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/contacts_web/live/contact_live/form_component.ex
defmodule ContactsWeb.ContactLive.FormComponent do
  use ContactsWeb, :live_component

  alias Contacts.CRM

  @impl true
  def update(%{contact: contact} = assigns, socket) do
    changeset = CRM.change_contact(contact)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"contact" => contact_params}, socket) do
    changeset =
      socket.assigns.contact
      |> CRM.change_contact(contact_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"contact" => contact_params}, socket) do
    save_contact(socket, socket.assigns.action, contact_params)
  end

  defp save_contact(socket, :edit, contact_params) do
    case CRM.update_contact(socket.assigns.contact, contact_params) do
      {:ok, _contact} ->
        {:noreply,
         socket
         |> put_flash(:info, "Contact updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_contact(socket, :new, contact_params) do
    case CRM.create_contact(contact_params) do
      {:ok, _contact} ->
        {:noreply,
         socket
         |> put_flash(:info, "Contact created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/contacts_web/live/contact_live/index.ex
defmodule ContactsWeb.ContactLive.Index do
  use ContactsWeb, :live_view

  alias Contacts.CRM
  alias Contacts.CRM.Contact

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :contacts, list_contacts())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Contact")
    |> assign(:contact, CRM.get_contact!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Contact")
    |> assign(:contact, %Contact{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Contacts")
    |> assign(:contact, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    contact = CRM.get_contact!(id)
    {:ok, _} = CRM.delete_contact(contact)

    {:noreply, assign(socket, :contacts, list_contacts())}
  end

  defp list_contacts do
    CRM.list_contacts()
  end
end

lib/contacts_web/live/contact_live/show.ex
defmodule ContactsWeb.ContactLive.Show do
  use ContactsWeb, :live_view

  alias Contacts.CRM

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:contact, CRM.get_contact!(id))}
  end

  defp page_title(:show), do: "Show Contact"
  defp page_title(:edit), do: "Edit Contact"
end

lib/contacts_web/live/live_helpers.ex
defmodule ContactsWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.contact_index_path(@socket, :index)}>
        <.live_component
          module={ContactsWeb.ContactLive.FormComponent}
          id={@contact.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.contact_index_path(@socket, :index)}
          contact: @contact
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/contacts_web/live/contact_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="contact-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :name %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>
  
    <%= label f, :title %>
    <%= text_input f, :title %>
    <%= error_tag f, :title %>
  
    <%= label f, :phone_number %>
    <%= text_input f, :phone_number %>
    <%= error_tag f, :phone_number %>
  
    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/contacts_web/live/contact_live/index.html.heex
<h1>Listing Contacts</h1>
<h1 class="text-indigo-500 text-3xl font-bold ml-9">Hello there I should be indigo!</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.contact_index_path(@socket, :index)}>
    <.live_component
      module={ContactsWeb.ContactLive.FormComponent}
      id={@contact.id || :new}
      title={@page_title}
      action={@live_action}
      contact={@contact}
      return_to={Routes.contact_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Phone number</th>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="contacts">
    <%= for contact <- @contacts do %>
      <tr id={"contact-#{contact.id}"}>
        <td><%= contact.name %></td>
        <td><%= contact.title %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.email %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.contact_show_path(@socket, :show, contact) %></span>
          <span><%= live_patch "Edit", to: Routes.contact_index_path(@socket, :edit, contact) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: contact.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Contact", to: Routes.contact_index_path(@socket, :new) %></span>

lib/contacts_web/live/contact_live/show.html.heex
<h1>Show Contact</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.contact_show_path(@socket, :show, @contact)}>
    <.live_component
      module={ContactsWeb.ContactLive.FormComponent}
      id={@contact.id}
      title={@page_title}
      action={@live_action}
      contact={@contact}
      return_to={Routes.contact_show_path(@socket, :show, @contact)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @contact.name %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @contact.title %>
  </li>

  <li>
    <strong>Phone number:</strong>
    <%= @contact.phone_number %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @contact.email %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.contact_show_path(@socket, :edit, @contact), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.contact_index_path(@socket, :index) %></span>